name: Build Python distribution

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Check commit message
      uses: kaisugi/action-regex-match@v1.0.1
      id: regex-match
      with:
        text: ${{ github.event.head_commit.message }}
        regex: '^[0-9]+\.[0-9]+\.[0-9]+$'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install build && 
        pip install twine && 
        pip install -r requirements.txt &&
        python3 -m build

    - name: Publish distribution
      if: ${{ steps.regex-match.outputs.match != '' }}
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    - name: Build Changelog
      if: ${{ steps.regex-match.outputs.match != '' }}
      id: changelog
      uses: ardalanamini/auto-changelog@v4.0.1
      with:
        mention-authors: false
        mention-new-contributors: false
        include-compare-link: false
        semver: false
        
    - name: Create Release
      if: ${{ steps.regex-match.outputs.match != '' }}
      uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }} 
        tag: ${{ github.event.head_commit.message }}
        name: Release v${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}